//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УП._01._01.Khachatryan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReadWriteDBEntities : DbContext
    {
        public ReadWriteDBEntities()
            : base("name=ReadWriteDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Complaint> Complaints { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<ReadingList> ReadingLists { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<RoleRequest> RoleRequests { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UnfreezeRequest> UnfreezeRequests { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
