//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УП._01._01.Khachatryan
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnfreezeRequest
    {
        public int RequestID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> BookID { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ReviewedAt { get; set; }
        public Nullable<int> ReviewedBy { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
